title: Rachel Gordon
logo:  # you can add own logo.
description:
baseurl: ""
url: https://rachelgordon.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Rachel Gordon
  image: '/assets/img/about.jpg'
  job: Hi there, welcome to my page!
  bio: |+
    <br />
    I am currently finishing my Master's in Data Science at <a href="https://www.luc.edu">Loyola University Chicago</a> and preparing to start my PhD at University of Chicago. 
    <br />
    I'm passionate about utilizing machine learning to improve the quality and accessibility of healthcare.
    <br />
  CV: https://drive.google.com/file/d/1dD4kfkNKCHcfA9JgnEpTU9Z4xMPm-bTQ/view?usp=sharing
  email: rachelgordon@uchicago.edu
  github: https://github.com/rachelngordon
  linkedin: https://www.linkedin.com/in/rachelngordon/
  last_update:  Apr 2024



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: rachelgordon # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
